name: CI Pipeline

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_U }}
        password: ${{ secrets.DOCKER_P }}

    - name: Build the Docker image
      run: docker build -t ${{ secrets.DOCKER_U }}/sessions-node-api:latest .

    - name: Push to DockerHub
      run: docker push ${{ secrets.DOCKER_U }}/sessions-node-api:latest
