name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login Dockerhub
      env: 
        DOCKER_U: ${{secrets.DOCKER_U}}
        DOCKER_P:  ${{secrets.DOCKER_P}}
      run:  docker login -u $DOCKER_U -p $DOCKER_P
    - name: Build the Docker image
      run: docker build -t sessions-node-api .
    - name: Push to Dockerhub
      run: docker push jojostev/sessions-node-api:latest
