name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_U }}
        password: ${{ secrets.DOCKER_P }}
    - name: Build the Docker image
      run: docker build -t sessions-node-api .
    - name: Push to Dockerhub
      run: docker push jojostev/sessions-node-api:latest
